### ISSUE TITLE
是否支持反“非正规应用商店”？

### ISSUE THREAD

**Issue by NikoCat233** [AoEiuV020/HookFanqie#2]
手机未Root，使用Lspatch默认破解番茄并加载模块，会提示非正规应用商店.
请问模块是否支持反“非正规应用商店”？

**Comment by AoEiuV020** [comment]
不了解这块，内置破解的话坑更多，更难隐藏，
实际上也不打算搞未root的支持，有点怕扩散惹事，所以仅支持root+xposed，主要是自用，
