### ISSUE TITLE
大佬牛逼，小弟甚是佩服

### ISSUE THREAD

**Issue by KOFKOY** [AoEiuV020/HookFanqie#3]
我用jadx 查看app源码，都是混淆过的，看不懂。
大佬都是咋看的，请大佬中指点

**Comment by AoEiuV020** [comment]
我也不是专业的，
混淆没办法，只能是找未混淆的部分一点点分析，通常activity和fragment是不混淆的，多少能看出点东西，
不过fanqie这个特别好搞，因为有很多硬编码的日志信息字符串，
直接搜“会员”两个字就能找到很多东西了，
其他只能看代码猜功能判断了，

**Comment by KOFKOY** [comment]
多谢大佬QAQ
