### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xanian001** [AoEiuV020/HookFanqie#4]
会提示版本不正规，然后小说内容不显示，试了旧版本的也不行，是安全检测有更新了吗

**Comment by AoEiuV020** [comment]
是lsposed吗？我这边只用这个，不支持lspatch之类的注入，
目标版本是和hook app版本一样的，最新5.8.5.18，
就算版本对不上应该也不会影响正常功能的， 除非你是注入apk触发了一些防破解的机制，

**Comment by xanian001** [comment]
怪不得，我用的lspatch




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 下午4:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AoEiuV020/HookFanqie] 报错 (Issue #4)





 
是lsposed吗？我这边只用这个，不支持lspatch之类的注入，
 目标版本是和hook app版本一样的，最新5.8.5.18，
 就算版本对不上应该也不会影响正常功能的， 除非你是注入apk触发了一些防破解的机制，

**Comment by xanian001** [comment]
关键我直接找个旧版本，都不改，都会报说让下最新版本，你用的5.8.5.18没有报错吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 下午4:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AoEiuV020/HookFanqie] 报错 (Issue #4)





 
是lsposed吗？我这边只用这个，不支持lspatch之类的注入，
 目标版本是和hook app版本一样的，最新5.8.5.18，
 就算版本对不上应该也不会影响正常功能的， 除非你是注入apk触发了一些防破解的机制，

**Comment by AoEiuV020** [comment]
这里5.8.5.18的hook做了去除更新，lsposed正常使用的话是不会提示更新的，主动检查更新也会说已经是最新版本，

**Comment by xanian001** [comment]
我应用汇上找旧版本找不到这个版本的番茄，这个版本之前的适用吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 下午4:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AoEiuV020/HookFanqie] 报错 (Issue #4)





 
这里5.8.5.18的hook做了去除更新，lsposed正常使用的话是不会提示更新的，主动检查更新也会说已经是最新版本，

**Comment by AoEiuV020** [comment]
不能保证适用，有混淆，我估计vip的hook会有效，其他应该不行，

**Comment by xanian001** [comment]
能上次个18版本的吗，网上都找不到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 下午4:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AoEiuV020/HookFanqie] 报错 (Issue #4)





 
不能保证适用，有混淆，我估计vip的hook会有效，其他应该不行，

**Comment by AoEiuV020** [comment]
是说上传目标版本的app吗？也有道理，我看看传哪里，
目前这项目支持的是5.8.5.18，小米应用商店里最新的是5.8.7.32，
这app更新太快了有点懒得适配新版本，

**Comment by AoEiuV020** [comment]
我在最新release增加了原apk文件，
https://github.com/AoEiuV020/HookFanqie/releases/tag/5.8.5.18

**Comment by xanian001** [comment]
实际测试，对应版本lspatch可以正常使用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AoEiuV020/HookFanqie"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月3日(星期四) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AoEiuV020/HookFanqie] 报错 (Issue #4)





 
我在最新release增加了原apk文件，
 https://github.com/AoEiuV020/HookFanqie/releases/tag/5.8.5.18

**Comment by AoEiuV020** [comment]
啊这，居然真的可以使用，我没试过以为不行的，看来lspatch还是挺强的，
行就这样吧，我并不打算维护这个lspatch支持，
另外建议不要随便传播lspatch破解后的apk，有点怕出事，

**Comment by xanian001** [comment]
肯定不会传播的，就自用，我就是安全公司的，只要不牟利不传播，自用没事




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月10日(星期四) 下午5:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AoEiuV020/HookFanqie] 报错 (Issue #4)





 
啊这，居然真的可以使用，我没试过以为不行的，看来lspatch还是挺强的，
 行就这样吧，我并不打算维护这个lspatch支持，
 另外建议不要随便传播lspatch破解后的apk，有点怕出事，

**Comment by xanian001** [comment]
我也以为不行来着，一直没试，今天无聊试了一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AoEiuV020/HookFanqie"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月10日(星期四) 下午5:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AoEiuV020/HookFanqie] 报错 (Issue #4)





 
啊这，居然真的可以使用，我没试过以为不行的，看来lspatch还是挺强的，
 行就这样吧，我并不打算维护这个lspatch支持，
 另外建议不要随便传播lspatch破解后的apk，有点怕出事，
